// Every text of the product page, in German and English. The scenes use the
// same structure in both languages, so the animations stay identical.
import type { Locale } from "@/lib/i18n";

export const GITHUB_URL = "https://github.com/yannicschuller/flowplan";

const de = {
  header: {
    home: "Flowplan, nach oben",
    sections: "Abschnitte",
    docs: "Doku",
    login: "Anmelden",
    register: "Registrieren",
    github: "Quellcode auf GitHub",
  },
  nav: {
    seitentypen: "Funktionen",
    "selbst-hosten": "Selbst hosten",
    sicherheit: "Sicherheit",
  } as Record<string, string>,
  demo: {
    try: "Demo ausprobieren",
    short: "Demo",
    busy: "Demo wird vorbereitet …",
    failed: "Die Demo konnte nicht starten.",
  },
  hero: {
    eyebrow: "Dokumente · Datenbanken · Whiteboards · Journal",
    title: "Alles, woran ihr arbeitet.",
    titleEm: "Open Source – bei uns oder bei euch.",
    text: "Dokumente, Datenbanken, Whiteboards, Journal, Projekte und Umfragen in einem Seitenbaum – gemeinsam und live.",
    facts: ["Open Source (AGPL)", "Server in Deutschland", "Selbst hostbar", "Kein Tracking"],
  },
  window: { team: "Team" },
  types: {
    doc: { label: "Dokumente", page: "Projekt-Kickoff" },
    db: { label: "Datenbanken", page: "Website-Relaunch" },
    board: { label: "Whiteboards", page: "Workshop Q4" },
    journal: { label: "Journal", page: "Mein Journal" },
    projects: { label: "Projekte", page: "Sprint 14" },
    survey: { label: "Umfragen", page: "Kundenumfrage" },
  },
  docScene: {
    title: "Projekt-Kickoff",
    meta: "Mara · heute bearbeitet",
    line: "Ziel: die neue Website bis 30. Oktober live.",
    slash: "/auf",
    slashItems: ["Aufgabenliste", "Tabelle", "Diagramm"],
    tasks: ["Texte finalisieren", "Bilder auswählen"],
    calloutTitle: "Entscheidung",
    callout: "Wir starten mit Deutsch und Englisch.",
    formulaLabel: "Budget",
    formula: "12 × 2.400 € = ",
    formulaResult: "28.800 €",
  },
  dbScene: {
    views: "Ansicht",
    records: ["Startseite gestalten", "Texte schreiben", "Bilder auswählen", "Übersetzungen", "Launch planen", "Feedback sammeln"],
    status: ["Offen", "In Arbeit", "Erledigt"],
    layouts: ["Tabelle", "Board", "Kalender", "Zeitleiste"],
    heads: ["Aufgabe", "Status", "Fällig"],
    days: ["Mo 12", "Di 13", "Mi 14", "Do 15", "Fr 16"],
    weeks: ["KW 42", "KW 43", "KW 44", "KW 45"],
    date: (day: number) => `${day}. Okt.`,
  },
  boardScene: {
    stickies: ["Onboarding kürzen", "Demo-Video", "Preise klarer"],
    page: "Projekt-Kickoff",
  },
  journalScene: {
    yesterday: "Freitag",
    yesterdayDate: "16. Oktober",
    note: "Guter Termin mit dem Kunden, Entwurf ist abgenommen.",
    done: "Entwurf präsentieren",
    open: ["Rechnung schreiben", "Mails beantworten"],
    today: "Heute",
    todayDate: "Samstag, 17. Oktober",
  },
  projectsScene: {
    columns: ["Offen", "In Arbeit", "Erledigt"],
    cards: ["Startseite gestalten", "Login reparieren", "Suche schneller machen", "Preise prüfen"],
    commit: "fixes WEB-14 · Ada",
    automation: "Automation: Erledigt am = heute",
    sprint: "Sprint 14",
    left: "noch 5 Punkte",
  },
  surveyScene: {
    question: "Wie wahrscheinlich empfiehlst du uns weiter?",
    stars: "Wie gefällt dir das neue Design?",
    send: "Absenden",
    results: "Ergebnisse",
    answers: "128 Antworten",
    bars: [
      ["Dokumente", 62],
      ["Datenbanken", 48],
      ["Whiteboards", 31],
    ] as [string, number][],
    average: "Ø 4,3 Sterne",
  },
  collabScene: {
    title: "Pressemitteilung",
    first: "Ab Montag gibt es die neue Website",
    firstLive: " in zwei Sprachen",
    secondMarked: "Alle Preise",
    second: " stehen direkt auf der Startseite",
    secondLive: ", ohne Formular",
    comment: "auch die Jahrespreise?",
    toast: "Aylin hat dich in „Pressemitteilung“ erwähnt",
    guestLink: "Gastlink",
    modes: ["Lesen", "Kommentieren", "Live bearbeiten"],
  },
  tour: {
    eyebrow: "Ein Seitenbaum für alles",
    title: "Jede Idee bekommt die Form, die sie braucht.",
    steps: {
      doc: {
        title: "Dokumente",
        lead: "Schreiben in Blöcken: Text, Aufgaben, Tabellen, Formeln und Diagramme auf einer Seite.",
        points: [
          "Befehle mit „/“, Blöcke per Griff, Sprachnotizen",
          "Aufgaben mit @Person und Fälligkeit",
          "Vorschläge machen, annehmen oder ablehnen",
          "Synchronisierte Blöcke und Versionen jeder Seite",
        ],
      },
      db: {
        title: "Datenbanken",
        lead: "Dieselben Einträge als Tabelle, Board, Kalender oder Zeitleiste – umschalten, nichts kopieren.",
        points: [
          "Filter in Gruppen, Sortierung, drei Gruppierungsebenen",
          "Formeln, Relationen und Rollups",
          "Wiederkehrende Einträge und Erinnerungen",
          "Jeder Eintrag ist auch eine eigene Seite",
        ],
      },
      board: {
        title: "Whiteboards",
        lead: "Eine unendliche Fläche für Workshops: Notizen, Formen, Verbindungen und Verweise auf eure Seiten.",
        points: [
          "Mindmaps mit Tab, Hilfslinien und Anordnen",
          "Laserpointer und „Folge mir“ beim Präsentieren",
          "Abstimmungen – auch verdeckt – und Timer",
          "Datenbank-Einträge als Karten, die aktuell bleiben",
        ],
      },
      journal: {
        title: "Journal",
        lead: "Jeden Tag eine neue Seite. Was gestern offen blieb, steht heute oben.",
        points: [
          "Tagesvorlage und Tracker für Stimmung, Schlaf oder Sport",
          "Offene Aufgaben wandern automatisch in den neuen Tag",
          "Serie, Heatmap und „An diesem Tag“",
          "Wochen- und Monatsrückblick, auf Wunsch mit PIN",
        ],
      },
      projects: {
        title: "Projekte & Tickets",
        lead: "Tickets mit Nummern, Sprints mit Burndown, Regeln, die Handgriffe übernehmen – nur wenn ihr sie einschaltet.",
        points: [
          "Ticketnummern wie WEB-123, Unteraufgaben und Epics",
          "Automationen, Workflows und WIP-Limits im Board",
          "Sprints, Zeiterfassung und Git-Commits am Eintrag",
          "Import aus Jira und Trello",
        ],
      },
      survey: {
        title: "Umfragen",
        lead: "Eine Umfrage wie bei SurveyMonkey, gebaut in wenigen Minuten – jede Antwort landet als Eintrag in der Datenbank.",
        points: [
          "19 Fragetypen: Sterne, NPS, Skalen, Matrix, Rangfolge …",
          "Bedingungen, Seiten, Schlussdatum und Antwortlimit",
          "Öffentlich teilen, Ergebnisse sofort ausgewertet",
          "Dashboards mit Kennzahlen aus mehreren Datenbanken",
        ],
      },
    },
  },
  views: {
    eyebrow: "Datenbanken",
    title: "Zehn Ansichten. Dieselben Daten.",
    text: "Eine Änderung im Board steht sofort auch im Kalender.",
    labels: ["Tabelle", "Board", "Kalender", "Zeitleiste", "Galerie", "Liste", "Feed", "Diagramm", "Formular", "Sprints"],
  },
  collab: {
    eyebrow: "Zusammenarbeit",
    title: "Gemeinsam an derselben Zeile.",
    text: "Mehrere Personen schreiben gleichzeitig, Kommentare hängen direkt am Text.",
    checks: [
      "Live-Bearbeitung in Dokumenten, Datenbanken und Whiteboards",
      "Kommentare, Reaktionen und Erwähnungen",
      "Gastlinks zum Lesen, Kommentieren oder Mitbearbeiten",
      "Öffentliche Seiten und Formulare ohne Konto",
    ],
  },
  index: {
    eyebrow: "Alle Funktionen",
    title: "Was drin ist.",
    docs: "Jede Funktion Schritt für Schritt in der Dokumentation",
    groups: [
      {
        title: "Dokumente",
        items: [
          "Blockeditor mit „/“-Befehlen",
          "Aufgabenlisten, Hinweise, Aufklapper",
          "Spalten bis drei nebeneinander",
          "Code mit Hervorhebung, Mermaid-Diagramme",
          "Formeln mit KaTeX",
          "Rechnen im Text, Vektoren, Funktionsgraphen",
          "Fotos markieren und bemalen",
          "Bilder, Dateien, Einbettungen, Linkkarten",
          "Erwähnungen von Personen und Seiten",
          "Aufgaben mit Person und Fälligkeit",
          "Synchronisierte Blöcke",
          "Vorschlagsmodus",
          "Sprachnotizen mit Transkription",
          "Fokusmodus mit Wortziel",
          "Versionen vergleichen, einzelne Absätze zurückholen",
          "Druck- und PDF-Layout",
        ],
      },
      {
        title: "Datenbanken",
        items: [
          "Zehn Ansichten auf dieselben Daten",
          "23 Feldtypen, darunter Formel, Relation, Rollup",
          "Filtergruppen und Sortierung",
          "Gruppen in drei Ebenen, Swimlanes",
          "Eigene Status-Spalten direkt im Board",
          "Berechnungen je Spalte",
          "Wiederholungen und Erinnerungen",
          "Datensatzseiten mit eigenem Layout",
          "Rechte pro Datensatz",
          "Einträge in andere Datenbanken kopieren oder verschieben",
          "Formulare, auch für Gäste",
          "Umfragen mit 19 Fragetypen, Bedingungen und Auswertung",
          "Kalender in beide Richtungen (CalDAV)",
          "CSV-Import und -Export",
        ],
      },
      {
        title: "Projekte & Tickets",
        items: [
          "Ticketnummern wie WEB-123, verlinkt im Text",
          "Unteraufgaben und Epics mit Fortschritt",
          "Sprints mit Backlog, Burndown und Velocity",
          "Automationen: wenn …, dann …",
          "Workflows mit erlaubten Wechseln und Pflichtfeldern",
          "WIP-Limits im Board",
          "Zeiterfassung mit Timer und Wochenauswertung",
          "Git-Anbindung für GitHub, GitLab und Gitea",
          "Dashboards mit Kennzahlen aus mehreren Datenbanken",
          "Kundenportal: Anfragen mit Status und Antworten",
          "Import aus Jira und Trello",
        ],
      },
      {
        title: "Whiteboards",
        items: [
          "Notizen, Formen, Text, Freihand mit Stiftdruck",
          "Mindmaps mit automatischer Anordnung",
          "Hilfslinien, Raster, Ausrichten und Stapeln",
          "Zettel nach Farbe, Person oder Stimmen sortieren",
          "Stempel, Laserpointer, „Folge mir“",
          "Abstimmungen, auch verdeckt, und Timer",
          "Bildersuche und Symbole",
          "Seiten und Datenbank-Einträge als Karten",
          "Vorlagen für Workshops, Kommentar-Pins",
        ],
      },
      {
        title: "Journal",
        items: [
          "Automatisch eine Seite pro Tag",
          "Tagesvorlage und Tracker",
          "Offene Aufgaben wandern mit",
          "Ort, Fotos und Termine des Tages",
          "Serie, Heatmap, „An diesem Tag“",
          "Wochen- und Monatsrückblick",
          "Sperre mit PIN",
        ],
      },
      {
        title: "Zusammenarbeit",
        items: [
          "Gleichzeitig bearbeiten mit Live-Cursorn",
          "Kommentare und Reaktionen",
          "Seiten folgen, gelesen von …",
          "Änderungen seit dem letzten Besuch",
          "Posteingang und Push-Benachrichtigungen",
          "Gastlinks: lesen, kommentieren, live bearbeiten",
          "Öffentliche Seiten, auch zum Kopieren",
          "Vorlagengalerie",
        ],
      },
      {
        title: "Ordnung",
        items: [
          "Arbeitsbereiche und Bereiche",
          "Gruppen und Seitenrechte",
          "Suche, auch in Dateien und Scans",
          "Befehle und Suche mit ⌘K",
          "Meine Aufgaben über alle Seiten und Datenbanken",
          "Graph der Verlinkungen",
          "Web-Clipper und Lesezeichen",
          "Favoriten, Papierkorb, Markdown-Export",
        ],
      },
      {
        title: "Betrieb",
        items: [
          "Open Source unter AGPL-3.0",
          "Ein Container mit SQLite, ohne Postgres und Redis",
          "Passkeys, Passwort oder Single Sign-on (OIDC)",
          "Rechte pro Bereich, Seite und Eintrag",
          "Laufende Sicherung nach S3",
          "Kein Tracking, keine KI-Auswertung",
          "Offline-Modus, Web-App fürs iPhone",
          "Desktop-Apps für macOS und Windows",
        ],
      },
    ],
  },
  selfHost: {
    eyebrow: "Open Source",
    title: "Bei uns in Deutschland.",
    titleEm: "Oder auf eurem Server.",
    text: "Freie Software unter der AGPL-3.0: fertig auf flowplan.org oder als ein Container auf eurem Server.",
    hosted: {
      title: "flowplan.org",
      note: "Fertig eingerichtet",
      points: ["Server in Deutschland", "Updates und Sicherungen inklusive", "Sofort loslegen, ohne Installation"],
    },
    self: {
      title: "Selbst hosten",
      note: "Auf eurem Server",
      points: [
        "Docker-Image für amd64 und arm64",
        "Anmeldung mit Passwort, Passkey oder eurem SSO",
        "Optional Sicherung nach S3, Whisper für Sprachnotizen",
      ],
    },
    guide: "Installationsanleitung",
    github: "Quellcode auf GitHub",
  },
  security: {
    eyebrow: "Sicherheit",
    title: "In Deutschland.",
    titleEm: "Eure Daten.",
    text: "Server in Deutschland, verschlüsselte Verbindungen, Rechte bis auf den einzelnen Eintrag. Gesichert – und von niemandem ausgewertet.",
    never: ["Keine KI-Auswertung", "Kein Tracking", "Keine Weitergabe an Dritte"],
    docs: "Alles zur Nutzung in der Dokumentation",
    terminal: "Sicherheit",
    rows: [
      ["Standort", "Rechenzentrum in Deutschland"],
      ["Verbindung", "HTTPS, verschlüsselt"],
      ["Anmeldung", "Passkey, Passwort oder SSO"],
      ["Rechte", "pro Bereich, Seite und Eintrag"],
      ["Sicherung", "regelmäßig, wiederherstellbar"],
    ],
    ok: "✓ Kein Tracking, keine Werbung",
    platforms: [
      { label: "macOS und Windows", note: "Desktop-App" },
      { label: "Browser", note: "Desktop und Mobil" },
      { label: "iPhone", note: "Web-App mit Push" },
      { label: "Offline", note: "pro Gerät zuschaltbar" },
    ],
  },
  final: { title: "Fang mit einer leeren Seite an." },
  footer: {
    tagline: "Dokumente, Datenbanken, Whiteboards und Journal. Open Source, betrieben in Deutschland.",
    more: "Weiteres",
    docs: "Dokumentation",
    templates: "Vorlagen",
    github: "GitHub",
  },
};

export type LandingCopy = typeof de;

const en: LandingCopy = {
  header: {
    home: "Flowplan, back to top",
    sections: "Sections",
    docs: "Docs",
    login: "Sign in",
    register: "Sign up",
    github: "Source code on GitHub",
  },
  nav: {
    seitentypen: "Features",
    "selbst-hosten": "Self-hosting",
    sicherheit: "Security",
  },
  demo: {
    try: "Try the demo",
    short: "Demo",
    busy: "Preparing the demo …",
    failed: "The demo could not start.",
  },
  hero: {
    eyebrow: "Documents · Databases · Whiteboards · Journal",
    title: "Everything you work on.",
    titleEm: "Open source – hosted by us or by you.",
    text: "Documents, databases, whiteboards, a journal, projects and surveys in one page tree – together and live.",
    facts: ["Open source (AGPL)", "Servers in Germany", "Self-hostable", "No tracking"],
  },
  window: { team: "Team" },
  types: {
    doc: { label: "Documents", page: "Project kickoff" },
    db: { label: "Databases", page: "Website relaunch" },
    board: { label: "Whiteboards", page: "Workshop Q4" },
    journal: { label: "Journal", page: "My journal" },
    projects: { label: "Projects", page: "Sprint 14" },
    survey: { label: "Surveys", page: "Customer survey" },
  },
  docScene: {
    title: "Project kickoff",
    meta: "Mara · edited today",
    line: "Goal: the new website live by 30 October.",
    slash: "/task",
    slashItems: ["Task list", "Table", "Chart"],
    tasks: ["Finalise copy", "Choose images"],
    calloutTitle: "Decision",
    callout: "We launch in German and English.",
    formulaLabel: "Budget",
    formula: "12 × €2,400 = ",
    formulaResult: "€28,800",
  },
  dbScene: {
    views: "View",
    records: ["Design home page", "Write copy", "Choose images", "Translations", "Plan launch", "Collect feedback"],
    status: ["To do", "In progress", "Done"],
    layouts: ["Table", "Board", "Calendar", "Timeline"],
    heads: ["Task", "Status", "Due"],
    days: ["Mon 12", "Tue 13", "Wed 14", "Thu 15", "Fri 16"],
    weeks: ["Wk 42", "Wk 43", "Wk 44", "Wk 45"],
    date: (day: number) => `Oct ${day}`,
  },
  boardScene: {
    stickies: ["Shorter onboarding", "Demo video", "Clearer pricing"],
    page: "Project kickoff",
  },
  journalScene: {
    yesterday: "Friday",
    yesterdayDate: "16 October",
    note: "Good meeting with the client, the draft is approved.",
    done: "Present the draft",
    open: ["Write the invoice", "Answer e-mails"],
    today: "Today",
    todayDate: "Saturday, 17 October",
  },
  projectsScene: {
    columns: ["Open", "In progress", "Done"],
    cards: ["Design the start page", "Fix the login", "Make search faster", "Check prices"],
    commit: "fixes WEB-14 · Ada",
    automation: "Automation: Done on = today",
    sprint: "Sprint 14",
    left: "5 points left",
  },
  surveyScene: {
    question: "How likely are you to recommend us?",
    stars: "How do you like the new design?",
    send: "Submit",
    results: "Results",
    answers: "128 answers",
    bars: [
      ["Documents", 62],
      ["Databases", 48],
      ["Whiteboards", 31],
    ] as [string, number][],
    average: "Avg. 4.3 stars",
  },
  collabScene: {
    title: "Press release",
    first: "From Monday the new website is online",
    firstLive: " in two languages",
    secondMarked: "All prices",
    second: " are right on the home page",
    secondLive: ", no form needed",
    comment: "yearly prices too?",
    toast: "Aylin mentioned you in “Press release”",
    guestLink: "Guest link",
    modes: ["View", "Comment", "Edit live"],
  },
  tour: {
    eyebrow: "One page tree for everything",
    title: "Every idea gets the shape it needs.",
    steps: {
      doc: {
        title: "Documents",
        lead: "Write in blocks: text, tasks, tables, formulas and diagrams on one page.",
        points: [
          "Commands with “/”, drag blocks by their handle, voice notes",
          "Tasks with @person and due date",
          "Suggest changes, accept or reject them",
          "Synced blocks and a version history for every page",
        ],
      },
      db: {
        title: "Databases",
        lead: "The same records as a table, board, calendar or timeline – switch views, copy nothing.",
        points: [
          "Grouped filters, sorting, three levels of grouping",
          "Formulas, relations and rollups",
          "Recurring records and reminders",
          "Every record is a page of its own",
        ],
      },
      board: {
        title: "Whiteboards",
        lead: "An infinite canvas for workshops: notes, shapes, connectors and links to your pages.",
        points: [
          "Mind maps with Tab, guides and auto layout",
          "Laser pointer and “follow me” when presenting",
          "Voting – also anonymous – and a timer",
          "Database records as cards that stay up to date",
        ],
      },
      journal: {
        title: "Journal",
        lead: "A new page every day. What stayed open yesterday is at the top today.",
        points: [
          "Daily template and trackers for mood, sleep or sport",
          "Open tasks move to the new day automatically",
          "Streak, heatmap and “on this day”",
          "Weekly and monthly review, optionally locked with a PIN",
        ],
      },
      projects: {
        title: "Projects & tickets",
        lead: "Tickets with numbers, sprints with a burndown, rules that take over routine steps – only when you switch them on.",
        points: [
          "Ticket numbers like WEB-123, subtasks and epics",
          "Automations, workflows and WIP limits on boards",
          "Sprints, time tracking and Git commits on the record",
          "Import from Jira and Trello",
        ],
      },
      survey: {
        title: "Surveys",
        lead: "A survey like SurveyMonkey, built in minutes – every answer lands as a record in the database.",
        points: [
          "19 question types: stars, NPS, scales, matrix, ranking …",
          "Conditions, pages, closing date and answer limit",
          "Share publicly, results analysed right away",
          "Dashboards with metrics from several databases",
        ],
      },
    },
  },
  views: {
    eyebrow: "Databases",
    title: "Ten views. The same data.",
    text: "A change on the board shows up in the calendar right away.",
    labels: ["Table", "Board", "Calendar", "Timeline", "Gallery", "List", "Feed", "Chart", "Form", "Sprints"],
  },
  collab: {
    eyebrow: "Collaboration",
    title: "Together on the same line.",
    text: "Several people write at the same time, comments stick right to the text.",
    checks: [
      "Live editing in documents, databases and whiteboards",
      "Comments, reactions and mentions",
      "Guest links to view, comment or edit",
      "Public pages and forms without an account",
    ],
  },
  index: {
    eyebrow: "All features",
    title: "What's inside.",
    docs: "Every feature step by step in the documentation",
    groups: [
      {
        title: "Documents",
        items: [
          "Block editor with “/” commands",
          "Task lists, callouts, toggles",
          "Up to three columns side by side",
          "Highlighted code, Mermaid diagrams",
          "Math with KaTeX",
          "Calculating in text, vectors, function graphs",
          "Mark up and draw on photos",
          "Images, files, embeds, link cards",
          "Mentions of people and pages",
          "Tasks with assignee and due date",
          "Synced blocks",
          "Suggestion mode",
          "Voice notes with transcription",
          "Focus mode with a word goal",
          "Compare versions, restore single paragraphs",
          "Print and PDF layout",
        ],
      },
      {
        title: "Databases",
        items: [
          "Ten views of the same data",
          "23 field types, including formula, relation, rollup",
          "Filter groups and sorting",
          "Groups on three levels, swimlanes",
          "Your own status columns right on the board",
          "Calculations per column",
          "Recurrence and reminders",
          "Record pages with their own layout",
          "Permissions per record",
          "Copy or move records to other databases",
          "Forms, also for guests",
          "Surveys with 19 question types, conditions and results",
          "Two-way calendar sync (CalDAV)",
          "CSV import and export",
        ],
      },
      {
        title: "Projects & tickets",
        items: [
          "Ticket numbers like WEB-123, linked in text",
          "Subtasks and epics with progress",
          "Sprints with backlog, burndown and velocity",
          "Automations: when …, then …",
          "Workflows with allowed changes and required fields",
          "WIP limits on boards",
          "Time tracking with a timer and weekly report",
          "Git connection for GitHub, GitLab and Gitea",
          "Dashboards with metrics from several databases",
          "Customer portal: requests with status and replies",
          "Import from Jira and Trello",
        ],
      },
      {
        title: "Whiteboards",
        items: [
          "Notes, shapes, text, freehand with pen pressure",
          "Mind maps with automatic layout",
          "Guides, grid, align and stack",
          "Sort notes by colour, person or votes",
          "Stamps, laser pointer, “follow me”",
          "Voting, also anonymous, and a timer",
          "Image search and icons",
          "Pages and database records as cards",
          "Workshop templates, comment pins",
        ],
      },
      {
        title: "Journal",
        items: [
          "A page for every day, automatically",
          "Daily template and trackers",
          "Open tasks move along",
          "Place, photos and appointments of the day",
          "Streak, heatmap, “on this day”",
          "Weekly and monthly review",
          "PIN lock",
        ],
      },
      {
        title: "Collaboration",
        items: [
          "Edit together with live cursors",
          "Comments and reactions",
          "Follow pages, seen by …",
          "Changes since your last visit",
          "Inbox and push notifications",
          "Guest links: view, comment, edit live",
          "Public pages, also to duplicate",
          "Template gallery",
        ],
      },
      {
        title: "Organisation",
        items: [
          "Workspaces and spaces",
          "Groups and page permissions",
          "Search, also in files and scans",
          "Commands and search with ⌘K",
          "My tasks across all pages and databases",
          "Graph of links",
          "Web clipper and bookmarks",
          "Favourites, trash, Markdown export",
        ],
      },
      {
        title: "Operations",
        items: [
          "Open source under the AGPL-3.0",
          "One container with SQLite, no Postgres or Redis",
          "Passkeys, password or single sign-on (OIDC)",
          "Permissions per space, page and record",
          "Continuous backup to S3",
          "No tracking, no AI analysis",
          "Offline mode, web app for iPhone",
          "Desktop apps for macOS and Windows",
        ],
      },
    ],
  },
  selfHost: {
    eyebrow: "Open source",
    title: "Hosted by us in Germany.",
    titleEm: "Or on your own server.",
    text: "Free software under the AGPL-3.0: ready to go on flowplan.org, or as one container on your server.",
    hosted: {
      title: "flowplan.org",
      note: "Ready to use",
      points: ["Servers in Germany", "Updates and backups included", "Start right away, nothing to install"],
    },
    self: {
      title: "Self-hosting",
      note: "On your server",
      points: [
        "Docker image for amd64 and arm64",
        "Sign-in with password, passkey or your SSO",
        "Optional S3 backups, Whisper for voice notes",
      ],
    },
    guide: "Installation guide",
    github: "Source code on GitHub",
  },
  security: {
    eyebrow: "Security",
    title: "In Germany.",
    titleEm: "Your data.",
    text: "Servers in Germany, encrypted connections, permissions down to a single record. Backed up – and analysed by no one.",
    never: ["No AI analysis", "No tracking", "No sharing with third parties"],
    docs: "Everything about using Flowplan in the documentation",
    terminal: "Security",
    rows: [
      ["Location", "Data centre in Germany"],
      ["Connection", "HTTPS, encrypted"],
      ["Sign-in", "Passkey, password or SSO"],
      ["Permissions", "per space, page and record"],
      ["Backup", "regular, restorable"],
    ],
    ok: "✓ No tracking, no ads",
    platforms: [
      { label: "macOS and Windows", note: "Desktop app" },
      { label: "Browser", note: "Desktop and mobile" },
      { label: "iPhone", note: "Web app with push" },
      { label: "Offline", note: "per device, on request" },
    ],
  },
  final: { title: "Start with a blank page." },
  footer: {
    tagline: "Documents, databases, whiteboards and journal. Open source, operated in Germany.",
    more: "More",
    docs: "Documentation",
    templates: "Templates",
    github: "GitHub",
  },
};

export const landingCopy: Record<Locale, LandingCopy> = { de, en };
